### PR TITLE
Testsite

### PR DESCRIPTION
**Pull request by nedasadeghi**
#### Please ensure this checklist is complete before creating the pull request.

- [ ] My branch name is the same as my `Site_ID`
- [ ] All of my data files are named `<site_ID>_data*.csv`
- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

To check boxes above, change `- [ ]` to `- [x]`

---

Once you create the pull request, we will automatically check your data files. \
If the test fails, you can see the output:
1. Click `Details` next to the failed job
2. Click `Run script` to view the output of the QC checks

If the QC script fails, we will work with you until your data pass all QC criteria.
To fix any issues that arise:
1. Correct the data files on your local copy of your forked repo
2. Add your updated data files to the staging area and commit your changes
3. Push your local repo to your remote fork

This pull request will automatically update when your forked repo changes.

_make sure your changes are on the same branch as the one you used to create this pull request_

### CODE REVIEW

**Comment by nedasadeghi** [comment]
@dmoracze I tried to check in a test dataset, however, one of the errors is:
parental_education entries need to be one of the following: 1, 2, 3, 777, shouldn't the range be 0,1,2,3?

**Comment by dmoracze** [comment]
@nedasadeghi that is a typo in the scripts output, I'll correct that. The criteria is:
```
        if not educ.isin([0,1,2,3,777]).all():
            errors.append('parental_education entries need to be one of the following: 1, 2, 3, 777')
```

**Comment by dmoracze** [comment]
@nedasadeghi your current data file has the following `parental_education` breakdown:
```
parental_education
2    24990
4    23933
3    17668
0     3409
```

**Comment by dmoracze** [comment]
Ok, I fixed the output of the `parental education error`
```
        if not educ.isin([0,1,2,3,777]).all():
            errors.append('parental_education entries need to be one of the following: 0, 1, 2, 3, 777')
```

**Comment by dmoracze** [comment]
The check for age is that `brain_behavior_measurement_date - dob` must equal `age`. Let me know if that's too strict and you want to put a range of acceptable values.

**Comment by nedasadeghi** [comment]
@dmoracze Yeah, I think it would be good to leave some room. How about plus/minus a month?

**Comment by dmoracze** [comment]
Ok, I made that change but your fork is out of data again. Here is the output of the new script checking your current data:
```
++ Date File Summary:
    Number of rows: 70000
    Number of columns: 19
    Number of correctly names columns: 19
    Number of unique subjects: 10000
    Age column: mean=167.0352, min=83, max=278
    Number of males: 4748
    Number of females: 5252

++ 6 ERRORS FOUND:
    age range is suspect, age(s) outside of 60 - 264 months found
    parental_education entries need to be one of the following: 0, 1, 2, 3, 777
    cbcl_externalizing_raw_score range is suspect, entries should be between 0 and 70
    iq range is suspect, entries should be between the broad range of 0 and 200
    wm_volume entries must all be greater than 0 and less than 1,000,000
    amygdala_volume entries must all be greater than 0 and less than 10,000
++ ----------
++ Finished with errors.
(base) dmoracze@MH02144726MLI SimulationCopy % git pull
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 3), reused 9 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), 10.86 MiB | 8.63 MiB/s, done.
From https://github.com/nedasadeghi/SimulationCopy
   8443270..f0fc664  testsite   -> origin/testsite
Updating 8443270..f0fc664
Fast-forward
 data/testsite/testsite_data1.csv | 140000 +++++++++++++++++++++++++++++++++---------------------------------
 data/testsite/testsite_data2.csv | 140000 +++++++++++++++++++++++++++++++++---------------------------------
 2 files changed, 140000 insertions(+), 140000 deletions(-)
(base) dmoracze@MH02144726MLI SimulationCopy % python tools/check_data.py testsite
++ 2 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data1.csv
++ Date File Summary:
    Number of rows: 70000
    Number of columns: 19
    Number of correctly names columns: 19
    Number of unique subjects: 10000
    Age column: mean=167.0352, min=83, max=278
    Number of males: 4748
    Number of females: 5252

++ 1 ERRORS FOUND:
    age range is suspect, age(s) outside of 60 - 264 months found
++ ----------
++ Checking data file: ./data/testsite/testsite_data2.csv
++ Date File Summary:
    Number of rows: 70000
    Number of columns: 19
    Number of correctly names columns: 19
    Number of unique subjects: 10000
    Age column: mean=167.0352, min=83, max=278
    Number of males: 4748
    Number of females: 5252

++ 1 ERRORS FOUND:
    age range is suspect, age(s) outside of 60 - 264 months found
++ ----------
++ Finished with errors.
```

**Pull request closed without merging**
