### PR TITLE
fixed the age

### PR DESCRIPTION
**Pull request by nedasadeghi**
#### Please ensure this checklist is complete before creating the pull request.

- [x] My branch name is the same as my `Site_ID`
- [x] All of my data files are named `<site_ID>_data*.csv`
- [x] All columns are present in my data file(s)
- [x] All columns are named properly
- [x] Data are coded according to the data dictionary
- [x] All measures are within the appropriate scales and distribution

To check boxes above, change `- [ ]` to `- [x]`

---

Once you create the pull request, we will automatically check your data files. \
If the test fails, you can see the output:
1. Click `Details` next to the failed job
2. Click `Run script` to view the output of the QC checks

If the QC script fails, we will work with you until your data pass all QC criteria.
To fix any issues that arise:
1. Correct the data files on your local copy of your forked repo
2. Add your updated data files to the staging area and commit your changes
3. Push your local repo to your remote fork

This pull request will automatically update when your forked repo changes.

_make sure your changes are on the same branch as the one you used to create this pull request_

### CODE REVIEW

**Comment by nedasadeghi** [comment]
@dmoracze can you change max age to 276? We initially said to have it less than 22 years, but I am suggesting the change to less than 23 as that gives 2 full extra years similar to our min age which is 5 ( two extra years before our start age of 7).

**Comment by dmoracze** [comment]
Yes I can, but I’m out of the office for the day. I can make this easy
change tomorrow morning.

**Comment by nedasadeghi** [comment]
no worries, I can try to make the change

**Comment by dmoracze** [comment]
Sure thing. My code is commented pretty well, it shouldn’t be hard to find
where to make that change.

**Comment by nedasadeghi** [comment]
@dmoracze I made the change for the age, when you get a chance can you add a check for 70000 rows and 10000 unique subjects? Thanks.

**Comment by dmoracze** [comment]
@nedasadeghi done!

45670ee9e2f8cb8c6ab747b38a01bb7e08c3b542

**Comment by nedasadeghi** [comment]
@dmoracze Great! Thank you.

**Comment by dmoracze** [comment]
I am closing this to clean up the repo, if you still want it open, you can re-open it

**Pull request closed without merging**
