### PR TITLE
add testsite data

### PR DESCRIPTION
**Pull request by nedasadeghi**
#### Please ensure this checklist is complete before creating the pull request.

- [ ] My branch name is the same as my `Site_ID`
- [ ] All of my data files are named `<site_ID>_data*.csv`
- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

To check boxes, change `- [ ]` to `- [x]`

Once you create the pull request, we will automatically check your data files. \
If the test fails, you can see the output:
1. Click `Details` next to the failed job
2. Click `Run script` to view the output of the QC checks

### CODE REVIEW

**Comment by dmoracze** [comment]
```
++ 1 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data1.csv
++ 7 ERRORS FOUND:
    Column names do not match data dictionary
    age range is suspect, age(s) outside of 60 - 264 months found
    brain_behavior_measurement_date minus dob should equal age, found entries where this is not true
    iq range is suspect, entries should be between the broad range of 0 and 200
    gm_volume entries must all be greater than 0 and less than 1,000,000
    wm_volume entries must all be greater than 0 and less than 1,000,000
    icv entries must all be greater than 0 and less than 5,000,000
++ Missing columns:
    amygdala_volume
    autism_diagnosis
    cbcl_attentionproblem_raw_score
    cbcl_externalizing_raw_score
    cbcl_internalizing_raw_score
    parental_education
++ Extra columns found:
    education
    scrn_asd
    simulatedDataBeh_long$cbcl_attentionproblem_raw_score * rnorm(numberOfRows, 
    simulatedDataExt_long$cbcl_externalizing_raw_score * rnorm(numberOfRows, 
    simulatedDataInt_long$cbcl_internalizing_raw_score * rnorm(numberOfRows, 
    simulatedDataVolAmg_long$amygdala_volume * rnorm(numberOfRows, 
++ ----------
++ Finished with errors.
```

**Comment by dmoracze** [comment]
```
++ 1 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data1.csv
++ 12 ERRORS FOUND:
    age range is suspect, age(s) outside of 60 - 264 months found
    brain_behavior_measurement_date minus dob should equal age, found entries where this is not true
    parental_education entries need to be one of the following: 1, 2, 3, 777
    cbcl_externalizing_raw_score range is suspect, entries should be between 0 and 70
    cbcl_internalizing_raw_score range is suspect, entries should be between 0 and 64
    cbcl_attentionproblem_raw_score range is suspect, entries should be between 0 and [20]
    iq range is suspect, entries should be between the broad range of 0 and 200
    gm_volume entries must all be greater than 0 and less than 1,000,000
    wm_volume entries must all be greater than 0 and less than 1,000,000
    amygdala_volume entries must all be greater than 0 and less than 10,000
    frontal_lobe_gm_thickness entries must all be greater than 0 and less than 5
    icv entries must all be greater than 0 and less than 5,000,000
++ ----------
++ Finished with errors.
```

**Comment by dmoracze** [comment]
```
++ 1 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data2.csv
++ 2 ERRORS FOUND:
    Column names do not match data dictionary
    parental_education entries need to be one of the following: 1, 2, 3, 777
++ Missing columns:
    subject_id
++ Extra columns found:
    subject_id 
++ ----------
++ Finished with errors.
```
re: `subject_id` weird. I have a meeting in 5 mins but I can look into this after

**Comment by dmoracze** [comment]
This helps, there is a bug to where the script will say `ERROR: There was a problem reading data file: {file}` if one of the dates are in the wrong format

**Comment by dmoracze** [comment]
```
++ 1 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data2.csv
++ 1 ERRORS FOUND:
    parental_education entries are not close to correct proportions
++ ----------
++ Finished with errors.
```

I think that's the best you can do with only 3 rows!

**Comment by dmoracze** [comment]
@nedasadeghi FYI the parental education proportion check is:
```
  # get proportions for 0, 1, 2, 3 (after rmoving 777)
  test = 1
  educ = educ[educ != 777]
  # 0 entries
  educ0 = (sum([i==0 for i in educ])/len(educ))*100
  if educ0 < 0.5 or educ0 > 10:
      test = 0
  # 1 entries
  educ1 = (sum([i==1 for i in educ])/len(educ))*100
  if educ1 < 30 or educ1 > 40:
      test = 0
  # 2 entries
  educ2 = (sum([i==2 for i in educ])/len(educ))*100
  if educ2 < 20 or educ2 > 30:
      test = 0
  # 3 entries
  educ3 = (sum([i==3 for i in educ])/len(educ))*100
  if educ2 < 30 or educ2 > 40:
      test = 0
  # check test
  if test==0:
      errors.append('parental_education entries are not close to correct proportions')
```
Let me know if you want something different

**Comment by nedasadeghi** [comment]
@dmoracze I am thinking maybe it's better if we remove the parental education constrain. Also, can you please add a check for the number of rows.

**Comment by dmoracze** [comment]
@nedasadeghi will do! I had it on my to do list for today but meetings ended up filling the day. It'll be the first thing I do tomorrow. I'll let you know when it's done.

**Comment by dmoracze** [comment]
@nedasadeghi @ivdvelpen 
I have made some changes to the check data script:
- removed the `parental_education` proportion check
- fixed a bug with date format checking
- added a summary report

For this pull request, the script output now looks like:
```
++ 1 data files found
++ ---------
++ Checking data file: ./data/testsite/testsite_data2.csv
++ Date File Summary:
    Number of rows: 3
    Number of columns: 19
    Number of correctly names columns: 19
    Number of unique subjects: 2
    Age column: mean=102.0, min=84, max=114
    Number of males: 1
    Number of females: 1

++ No errors found!
++ ----------
++ Finished without errors!
```

Unfortunately for you to have this new script run on either of your open pull requests, you'll need to delete your fork and start again, because your fork has the old version of `check_data.py`

Please let me know if you would like me to add more to the summary report

**Pull request closed without merging**
