### PR TITLE
add isatest data

### PR DESCRIPTION
**Pull request by ivdvelpen**
## Please ensure this checklist is complete before creating the pull request.

- [x] All of my data files are named `<site_ID>_data*.csv`
- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

To check boxes, change `- [ ]` to `- [x]`

### CODE REVIEW

**Comment by dmoracze** [comment]
@ivdvelpen I did something stupid in the checker script and there was a bug.
I've fixed it now and I ran it on your data. It works now.

Can we try this one more time?

**Comment by dmoracze** [comment]
I'm learning a lot lol

**Comment by ivdvelpen** [comment]
No worries! From which step would you like me to start again?

**Comment by dmoracze** [comment]
From the beginning because your fork will need my updated code. So delete your fork and re-fork the main repo.

Thank you!

**Pull request closed without merging**
