### PR TITLE
 add isatest data

### PR DESCRIPTION
**Pull request by ivdvelpen**
## Please ensure this checklist is complete before creating the pull request.

- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

### CODE REVIEW

**Comment by dmoracze** [comment]
Hi @ivdvelpen - it looks like your files are named:
```
simulation1.csv
simulation2.csv
simulation3_with_iq.csv
```

They should be named <site_ID>_dataX.csv. So if your site ID is `isatest`:
```
isatest_data1.csv
isatest_data2.csv
isatest_data3.csv
```

Happy to figure out a better way to do this if you have suggestions. I need to add the file naming format in the pull request template.

**Comment by dmoracze** [comment]
```
++ 3 data files found
++ Checking data file: ./data/isatest/isatest_data1.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary 
    Please correct column names before proceeding
++ Checking data file: ./data/isatest/isatest_data2.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary 
    Please correct column names before proceeding
++ Checking data file: ./data/isatest/isatest_data3.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary 
    Please correct column names before proceeding
++ Finished with errors.
```

**Comment by dmoracze** [comment]
This is helpful - I need to update the QC script to print out the mismatch in column names.

**Comment by dmoracze** [comment]
Right now it says your column names are incorrect, but the files are too big to view in GitHub. Let me work on the QC script and I'll rerun the check when I'm ready

**Comment by ivdvelpen** [comment]
Great! The column names are indeed incorrect. I guess the QC script can't perform the rest of the checks if it fails on things like column names, right?

**Comment by dmoracze** [comment]
Yes, that's how it is currently set up since all the next steps are column-wise checking. I suppose a better solution would be to find the mismatched columns, print that out, but then proceed to QC the correct columns. I can make that change.

**Comment by dmoracze** [comment]
@ivdvelpen I have updated the `check_data.py` script. However, it looks like I cannot run the new script in this pull request since your repo does not have the updated script. It might be possible but I'm not completely fluent in GitHub.

Can you try the entire thing again? You can delete your fork by:
```
git push --delete origin isatest
```
And delete your branch by
```
git checkout main
git branch -D isatest
```
Then run
```
git pull
```
To download the most recent version of the repo.

**Pull request closed without merging**
