### PR TITLE
add isatest3 data

### PR DESCRIPTION
**Pull request by ivdvelpen**
#### Please ensure this checklist is complete before creating the pull request.

- [x] All of my data files are named `<site_ID>_data*.csv`
- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

To check boxes, change `- [ ]` to `- [x]`

Once you create the pull request, we will automatically check your data files. \
If the test fails, you can see the output:
1. Click `Details` next to the failed job
2. Click `Run script` to view the output of the QC checks

### CODE REVIEW

**Comment by dmoracze** [comment]
@ivdvelpen your branch name is isatest3 but the branch name needs to equal the site_ID, which corresponds to the directory name in `data`

**Comment by dmoracze** [comment]
I will update the template pull request to add this check box

**Comment by ivdvelpen** [comment]
already saw it, lol end of the day is getting me

**Comment by ivdvelpen** [comment]
Not sure how I can delete the failed data from this pull request? The updated datasets are visible in the pull request to me, but the QC is not taking them

**Comment by dmoracze** [comment]
It's working!
Here is the output:
```
++ 3 data files found
++ ---------
++ Checking data file: ./data/isatest3/isatest3_data1.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary
++ Missing columns:
    cbcl_attentionproblem_raw_score
    sex
    icv
    parental_education
    dob
    frontal_lobe_gm_thickness
    amygdala_volume
    cbcl_internalizing_raw_score
    hippo_volume
    site_id
    autism_diagnosis
    gm_volume
    brain_behavior_measurement_date
    wave_number
    wm_volume
    iq
    subject_id
    cbcl_externalizing_raw_score
++ Extra columns found:
    gmVol4
    amygVol1
    external5
    (Intercept)
    gmVol1
    scrn_asd1
    gmVol2
    attention2
    age5
    attention7
    internal6
    fluidiq
    attention6
    internal3
    external3
    gmVol7
    Unnamed: 0
    amygVol6
    external7
    attention4
    age6
    gmVol5
    external4
    attention1
    internal7
    internal1
    attention3
    amygVol7
    external2
    internal2
    amygVol2
    external1
    external6
    age2
    internal5
    sexM
    education
    gmVol3
    age3
    amygVol4
    totalcomp
    age4
    age7
    amygVol5
    attention5
    gmVol6
    age1
    internal4
    amygVol3
++ ----------
++ Checking data file: ./data/isatest3/isatest3_data2.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary
++ Missing columns:
    cbcl_attentionproblem_raw_score
    sex
    icv
    parental_education
    dob
    frontal_lobe_gm_thickness
    amygdala_volume
    cbcl_internalizing_raw_score
    hippo_volume
    site_id
    autism_diagnosis
    gm_volume
    brain_behavior_measurement_date
    wave_number
    wm_volume
    iq
    subject_id
    cbcl_externalizing_raw_score
++ Extra columns found:
    gmVol4
    amygVol1
    external5
    (Intercept)
    gmVol1
    scrn_asd1
    gmVol2
    attention2
    age5
    attention7
    internal6
    fluidiq
    attention6
    internal3
    external3
    gmVol7
    Unnamed: 0
    amygVol6
    external7
    attention4
    age6
    gmVol5
    external4
    attention1
    internal7
    internal1
    attention3
    amygVol7
    external2
    internal2
    amygVol2
    external1
    external6
    age2
    internal5
    sexM
    education
    gmVol3
    age3
    amygVol4
    totalcomp
    age4
    age7
    amygVol5
    attention5
    gmVol6
    age1
    internal4
    amygVol3
++ ----------
++ Checking data file: ./data/isatest3/isatest3_data3.csv
++ 1 ERRORS FOUND:
    Column names do not match data dictionary
++ Missing columns:
    cbcl_attentionproblem_raw_score
    sex
    icv
    parental_education
    dob
    frontal_lobe_gm_thickness
    amygdala_volume
    cbcl_internalizing_raw_score
    hippo_volume
    site_id
    autism_diagnosis
    gm_volume
    brain_behavior_measurement_date
    wave_number
    wm_volume
    iq
    subject_id
    cbcl_externalizing_raw_score
++ Extra columns found:
    gmVol4
    amygVol1
    external5
    (Intercept)
    gmVol1
    scrn_asd1
    gmVol2
    attention2
    nviq
    age5
    attention7
    internal6
    fluidiq
    attention6
    internal3
    external3
    gmVol7
    Unnamed: 0
    amygVol6
    external7
    attention4
    age6
    gmVol5
    external4
    attention1
    internal7
    internal1
    attention3
    amygVol7
    external2
    internal2
    amygVol2
    external1
    external6
    viq
    age2
    internal5
    sexM
    education
    gmVol3
    age3
    amygVol4
    totalcomp
    age4
    age7
    amygVol5
    attention5
    gmVol6
    age1
    internal4
    amygVol3
++ ----------
++ Finished with errors.
```

**Comment by dmoracze** [comment]
Let me know if there is a more helpful output

**Comment by dmoracze** [comment]
If you change the data files and commit them, the QC script will run each time. This helps for iterative fixing of issues.

**Comment by ivdvelpen** [comment]
This looks great! Thanks for being on standby and testing today :)

**Comment by dmoracze** [comment]
Sure thing! I'm going to add a couple lines that sort the missing columns and extra columns alphabetically, just in case there's a lot as in this example

**Comment by nedasadeghi** [comment]
@ivdvelpen can you try to submit the example file? It has the right column names (it only has 3 rows, but I don't think currently we are checking for the number of rows)

**Comment by dmoracze** [comment]
@nedasadeghi we are not.

Now that this is working, tomorrow I'll add a little summary report at the top or bottom of the output.
- subject / sex / wave count
- mean and range of measures (or count for ASD)

Let me know if you want to see any more summary info

**Comment by dmoracze** [comment]
@ivdvelpen you can add more data files to this pull request, they just need to be named `isatest3_data*.csv`.

To remove files you can:
```
git rm data/isatest3/isatest_data*
git commit -m 'remove old data files'
git push origin isatest3
```

**Comment by nedasadeghi** [comment]
@ivdvelpen I just emailed it

**Pull request closed without merging**
